# Generated by Django 3.1.2 on 2021-03-29 15:43

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Technologie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('adresse', models.CharField(max_length=100)),
                ('role', models.CharField(choices=[('Admin', 'Admin'), ('Investisseur', 'Investisseur'), ('Porteur Projet', 'Porteur Projet')], max_length=15)),
                ('date_inscription', models.DateTimeField(auto_now_add=True)),
                ('password', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Administrateur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projet_api.utilisateur')),
            ],
            bases=('projet_api.utilisateur',),
        ),
        migrations.CreateModel(
            name='Investisseur',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projet_api.utilisateur')),
                ('contact', models.CharField(max_length=20)),
            ],
            bases=('projet_api.utilisateur',),
        ),
        migrations.CreateModel(
            name='Porteur_Projet',
            fields=[
                ('utilisateur_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='projet_api.utilisateur')),
                ('contact', models.CharField(max_length=20)),
                ('num_passport', models.IntegerField()),
                ('KBIS', models.CharField(max_length=100, unique=True)),
                ('depot_KBIS', models.FileField(upload_to='KBIS/')),
            ],
            bases=('projet_api.utilisateur',),
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('montant', models.IntegerField(default=0)),
                ('duree', models.IntegerField()),
                ('date_creation', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(default='default.jpg', upload_to='images/')),
                ('document', models.FileField(upload_to='document/')),
                ('validation', models.BooleanField(default=False)),
                ('supprime', models.BooleanField(default=False)),
                ('statut', models.CharField(choices=[('En attente de financement', 'En attente de financement'), ('Financé', 'Financé')], max_length=30)),
                ('technologie', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='projet_api.technologie')),
            ],
        ),
        migrations.CreateModel(
            name='Investir',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_api.projet')),
                ('investisseur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_api.investisseur')),
            ],
        ),
    ]
