# Generated by Django 3.1.2 on 2021-03-29 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projet_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='porteur',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projet_api.porteur_projet'),
        ),
    ]
