# Generated by Django 3.1.2 on 2021-04-01 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_api', '0002_projet_porteur'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projet',
            name='supprime',
        ),
        migrations.AlterField(
            model_name='projet',
            name='statut',
            field=models.CharField(choices=[('En attente de financement', 'En attente de financement'), ('Financé', 'Financé'), ('Rejété', 'Rejété')], max_length=30),
        ),
    ]
