# Generated by Django 3.1.2 on 2021-04-09 04:29

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('projet_api', '0004_auto_20210401_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tache',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('duree', models.IntegerField(default=0)),
                ('debut', models.DateField()),
                ('fin', models.DateField()),
                ('image', models.ImageField(blank=True, upload_to='images/taches/')),
                ('statut', models.CharField(choices=[('En attente', 'En attente'), ('En cours', 'En cours'), ('Terminé', 'Terminé')], default='En attente', max_length=20)),
                ('avancement', models.IntegerField(default=0)),
                ('projet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projet_api.projet')),
            ],
        ),
    ]
