# Generated by Django 3.1.2 on 2021-04-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_api', '0005_tache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tache',
            name='debut',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='tache',
            name='fin',
            field=models.DateField(null=True),
        ),
    ]
