# Generated by Django 3.1.2 on 2021-04-18 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projet_api', '0006_auto_20210409_0631'),
    ]

    operations = [
        migrations.AlterField(
            model_name='technologie',
            name='description',
            field=models.TextField(null=True),
        ),
    ]
